// client/makc2022--angular/src/app/app.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { ActivatedRoute, Params, Router } from '@angular/router';
import {
  I18NEXT_NAMESPACE,
  I18NEXT_SERVICE,
  ITranslationService,
} from 'angular-i18next';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [
    {
      provide: I18NEXT_NAMESPACE,
      useValue: 'app',
    },
  ],
})
export class AppComponent implements OnInit {
  title = '@@title';

  languages: { text: string; value: string; selected: boolean }[] = [];

  constructor(
    @Inject(I18NEXT_SERVICE) private i18NextService: ITranslationService,
    private router: Router,
    private activatedRoute: ActivatedRoute
  ) {
    const languages = i18NextService.options.supportedLngs as string[];

    for (const language of languages) {
      let text = '';

      switch (language) {
        case 'en':
          text = 'English';
          break;
        case 'ru':
          text = 'Русский';
          break;
      }

      this.languages.push({ text, value: language, selected: false });
    }
  }

  ngOnInit(): void {
    this.i18NextService.events.initialized.subscribe((e) => {
      if (e) {
        for (const language of this.languages) {
          language.selected = language.value === this.i18NextService.language;
        }
      }
    });
  }

  onLanguageChange(event: Event): void {
    const lang = (event.target as HTMLSelectElement).value;

    if (lang !== this.i18NextService.language) {
      this.i18NextService.changeLanguage(lang).then(() => {
        const queryParams: Params = { lng: lang };

        this.router
          .navigate([], {
            relativeTo: this.activatedRoute,
            queryParams: queryParams,
            queryParamsHandling: 'merge', // remove to replace all query params by provided
          })
          .then(() => {
            document.location.reload();
          });
      });
    }
  }
}

<h1>{{ title | i18nextCap }}</h1>
<div class="top-menu">
  <nav>
    <a routerLink="/dashboard">Dashboard</a>
    <a routerLink="/heroes">Heroes</a>
  </nav>
  <select (change)="onLanguageChange($event)">
    <option
      *ngFor="let language of languages"
      [value]="language.value"
      [selected]="language.selected"
    >
      {{ language.text }}
    </option>
  </select>
</div>
<router-outlet></router-outlet>
<app-messages></app-messages>

// client/makc2022--redux/src/App.tsx
import React from 'react';
import { Link, Outlet, useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ModuleContext, defaultModule } from './contexts';
import styles from './App.module.css';
import { Messages } from './components/Messages';
import './i18n';

function App(): React.ReactElement {
  const { t, i18n } = useTranslation(['App']);

  const [searchParams, setSearchParams] = useSearchParams();

  const languages: { text: string; value: string }[] = [];

  const supportedLngs = i18n.options.supportedLngs as string[];

  supportedLngs.forEach((lng) => {
    let text = '';

    switch (lng) {
      case 'en':
        text = 'English';
        break;
      case 'ru':
        text = 'Русский';
        break;
      default:
        return;
    }

    languages.push({ text, value: lng });
  });

  function handleLanguageChange(
    event: React.ChangeEvent<HTMLSelectElement>
  ): void {
    const lang = event.target.value;

    if (lang !== i18n.language) {
      i18n.changeLanguage(lang).then(() => {
        searchParams.set('lng', lang);

        setSearchParams(searchParams);
      });
    }
  }

  return (
    <ModuleContext.Provider value={defaultModule}>
      <div className={styles.app}>
        <h1>{t('@@title')}</h1>
        <div className={styles['top-menu']}>
          <nav>
            <Link to='dashboard'>Dashboard</Link>
            <Link to='heroes'>Heroes</Link>
          </nav>
          <select onChange={handleLanguageChange} defaultValue={i18n.language}>
            {languages.map((language) => (
              <option key={language.value} value={language.value}>
                {language.text}
              </option>
            ))}
          </select>
        </div>
        <Outlet />
        <Messages />
      </div>
    </ModuleContext.Provider>
  );
}

export default App;
