// client/makc2022--angular/src/app/components/messages/messages.component.ts
import { getMessagesSuccess } from './../messages/messages.slice';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { MessageService } from '../../services/message.service';
import { clear, selectMessages } from './messages.slice';
import { I18NEXT_NAMESPACE } from 'angular-i18next';

@Component({
  selector: 'app-messages',
  templateUrl: './messages.component.html',
  styleUrls: ['./messages.component.css'],
  providers: [
    {
      provide: I18NEXT_NAMESPACE,
      useValue: 'components/messages',
    },
  ],
})
export class MessagesComponent implements OnDestroy, OnInit {
  messages$ = this.store.select(selectMessages);
  messagesLength = 0;
  subscriptionId = '';

  constructor(public messageService: MessageService, private store: Store) {
    this.messages$.subscribe((messages) => {
      this.messagesLength = messages.length;
    });
  }

  clearMessages(): void {
    this.messageService.clear();
    this.store.dispatch(clear());
  }

  ngOnDestroy(): void {
    this.messageService.unsubscribe(this.subscriptionId);
    this.store.dispatch(clear());
  }

  ngOnInit(): void {
    this.subscriptionId = this.messageService.subscribe((messages) => {
      this.store.dispatch(getMessagesSuccess({ messages }));
    });
  }
}

<div *ngIf="messagesLength">
  <h2>{{ "@@title" | i18nextCap }}</h2>
  <button class="clear" (click)="clearMessages()">
    {{ "@@action-clear-messages" | i18nextCap }}
  </button>
  <div *ngFor="let message of messages$ | async">{{ message }}</div>
</div>

// client/makc2022--redux/src/components/Messages/index.tsx
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useAppDispatch, useAppSelector } from '../../app/hooks';
import { useModuleContext } from '../../contexts';
import styles from './Messages.module.css';
import { clear, selectMessages, setMessages } from './messagesSlice';

export function Messages(): React.ReactElement | null {
  const { messageService } = useModuleContext();

  const { t } = useTranslation(['components/Messages']);

  const messages = useAppSelector(selectMessages);

  const dispatch = useAppDispatch();

  useEffect(() => {
    const subscriptionId = messageService.subscribe((messagesValue) => {
      dispatch(setMessages(messagesValue));
    });
    return () => {
      messageService.unsubscribe(subscriptionId);
      dispatch(clear());
    };
  }, [dispatch, messageService]);

  if (!messages.length) {
    return null;
  }

  return (
    <div className={styles.messages}>
      <h2>{t('@@title')}</h2>
      <button
        type='button'
        className={styles.clear}
        onClick={() => messageService.clear()}
      >
        {t('@@action-clear-messages')}
      </button>
      {messages.map((message, index) => (
        <div key={index}>{message}</div>
      ))}
    </div>
  );
}
