// client/makc2022--redux/src/views/Heroes/index.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { createHero, Hero } from '../../models/Hero';
import { useModuleContext } from '../../contexts';
import { useAppDispatch, useAppSelector } from '../../app/hooks';
import styles from './Heroes.module.css';
import {
  addHeroAsync,
  clear,
  deleteHeroAsync,
  getHeroesAsync,
  selectHeroes,
} from './heroesSlice';

export function Heroes(): React.ReactElement {
  const { heroService } = useModuleContext();

  const { t } = useTranslation(['views/Heroes']);

  const heroes = useAppSelector(selectHeroes);

  const [newHero, setNewHero] = useState(createHero());

  const dispatch = useAppDispatch();

  const inputs = {
    newHeroName: {
      id: 'new-hero',
      name: 'new-hero',
    },
  };

  useEffect(() => {
    dispatch(getHeroesAsync({ heroService }));
    return () => {
      dispatch(clear());
    };
  }, [dispatch, heroService]);

  function handleInputChange(event: React.ChangeEvent<HTMLInputElement>): void {
    const { target } = event;

    if (target.name === inputs.newHeroName.name) {
      setNewHero({ ...newHero, name: target.value });
    }
  }

  function addNewHero(): void {
    if (newHero.name) {
      newHero.name = newHero.name.trim();
    }
    if (!newHero.name) {
      return;
    }
    dispatch(addHeroAsync({ heroService, hero: newHero })).then(() => {
      setNewHero(createHero());
    });
  }

  function deleteHero(hero: Hero): void {
    dispatch(deleteHeroAsync({ heroService, hero }));
  }

  return (
    <div className={styles.heroes}>
      <h2>{t('@@title')}</h2>
      <div>
        <label htmlFor={inputs.newHeroName.id}>{t('@@hero-name')}: </label>
        <input
          id={inputs.newHeroName.id}
          name={inputs.newHeroName.name}
          value={newHero.name}
          onChange={handleInputChange}
        />
        <button
          className={styles['add-button']}
          type='button'
          onClick={addNewHero}
        >
          {t('@@action-add-hero')}
        </button>
      </div>
      <ul>
        {heroes.map((hero) => (
          <li key={hero.id}>
            <Link to={`/detail/${hero.id}`}>
              <span className={styles.badge}>{hero.id}</span> {hero.name}
            </Link>
            <button
              className={styles.delete}
              type='button'
              title={t('@@action-delete-hero')}
              onClick={() => deleteHero(hero)}
            >
              x
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}

// client/makc2022--angular/src/app/views/heroes/heroes.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { I18NEXT_NAMESPACE } from 'angular-i18next';
import { Hero } from '../../models/hero';
import { HeroService } from '../../services/hero.service';
import {
  addHero,
  addHeroSuccess,
  clear,
  deleteHero,
  deleteHeroSuccess,
  getHeroes,
  getHeroesSuccess,
  selectAddedHero,
  selectDeletedHero,
  selectHeroes,
} from './heroes.slice';

@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.css'],
  providers: [
    {
      provide: I18NEXT_NAMESPACE,
      useValue: 'views/heroes',
    },
  ],
})
export class HeroesComponent implements OnDestroy, OnInit {
  addeedHero$ = this.store.select(selectAddedHero);
  deletedHero$ = this.store.select(selectDeletedHero);
  heroes$ = this.store.select(selectHeroes);

  inputs = {
    newHeroName: {
      id: 'new-hero',
    },
  };

  constructor(private store: Store) {}

  getHeroes(): void {
    this.store.dispatch(getHeroes());
  }

  ngOnDestroy(): void {
    this.store.dispatch(clear());
  }

  ngOnInit(): void {
    this.getHeroes();
  }

  add(name: string): void {
    name = name.trim();
    if (!name) {
      return;
    }
    this.store.dispatch(addHero({ addedHero: { name } as Hero }));
    this.getHeroes();
  }

  delete(hero: Hero): void {
    this.store.dispatch(deleteHero({ id: hero.id }));
    this.getHeroes();
  }
}

<h2>{{ "@@title" | i18nextCap }}</h2>
<div>
  <label [for]="inputs.newHeroName.id"
    >{{ "@@hero-name" | i18nextCap }}:
  </label>
  <input [id]="inputs.newHeroName.id" #heroName />

  <!-- (click) passes input value to add() and then clears the input -->
  <button class="add-button" (click)="add(heroName.value); heroName.value = ''">
    {{ "@@action-add-hero" | i18next }}
  </button>
</div>
<ul class="heroes">
  <li *ngFor="let hero of heroes$ | async">
    <a routerLink="/detail/{{ hero.id }}">
      <span class="badge">{{ hero.id }}</span> {{ hero.name }}
    </a>
    <button
      class="delete"
      title="{{ '@@action-delete-hero' | i18next }}"
      (click)="delete(hero)"
    >
      x
    </button>
  </li>
</ul>
